<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN"
  "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
  <head>
    <title>いるか</title>
    <meta http-equiv="Content-Type" content="text/html;charset=utf-8" />
    <style type="text/css">
      img {border-width: 0}
      * {font-family:'Lucida Grande', sans-serif;}
    </style>
  </head>
  <body>
    <div>
      <h2><a href="/">いるか</a></h2>
      
      <p>ご利用にはツイッター認証が必要です。</p>
      
	    <p>
	      <pre>
	        <?php print_r($content); ?>
	      </pre>
	    </p>
      <hr />
    </div>
  </body>
</html>
